name: Apply Core Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::000363030077:role/terraform-github-role
          aws-region: us-east-1

      - name: Apply infrastructure
        run: terraform apply -auto-approve
        working-directory: terraform/core-infra

  notify_failure:
    needs: [terraform-apply]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Notify Slack if any job failed
        if: ${{ needs.terraform-apply.result == 'failure' }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.CHANNEL_ID }}
            text: "ðŸš¨ *Terraform Pipeline Failed*\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nWorkflow: ${{ github.workflow }}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
